// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PromptSpark.Domain.Data;

#nullable disable

namespace PromptSpark.Migrations.HazletonGPTDb
{
    [DbContext(typeof(GPTDbContext))]
    [Migration("20240421194850_AddOutputType")]
    partial class AddOutputType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("PromptSpark.ServiceDefinition.Database.GPTDefinition", b =>
                {
                    b.Property<int>("DefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceDescriptionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Temperature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("DefinitionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Definitions");
                });

            modelBuilder.Entity("PromptSpark.ServiceDefinition.Database.GPTDefinitionResponse", b =>
                {
                    b.Property<int>("ServiceDefintionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefinitionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ElapsedMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceDescriptionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserPromptId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemResponse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Temperature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserExpectedResponse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TestPrompt")
                        .HasColumnType("TEXT");

                    b.HasKey("ServiceDefintionId");

                    b.HasIndex("DefinitionId");

                    b.HasIndex("UserPromptId");

                    b.ToTable("DefinitionResponses");
                });

            modelBuilder.Entity("PromptSpark.ServiceDefinition.Database.GPTDefinitionType", b =>
                {
                    b.Property<string>("DefinitionType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceDescriptionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("DefinitionType");

                    b.HasIndex("DefinitionType")
                        .IsUnique();

                    b.ToTable("DefinitionTypes");
                });

            modelBuilder.Entity("PromptSpark.ServiceDefinition.Database.GPTUserPrompt", b =>
                {
                    b.Property<int>("ServiceDefintionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserExpectedResponse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TestPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ServiceDefintionId");

                    b.HasIndex("TestPrompt")
                        .IsUnique();

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("PromptSpark.ServiceDefinition.Database.GPTDefinitionResponse", b =>
                {
                    b.HasOne("PromptSpark.ServiceDefinition.Database.GPTDefinition", "Definition")
                        .WithMany("GPTResponses")
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PromptSpark.ServiceDefinition.Database.GPTUserPrompt", "Response")
                        .WithMany("GPTResponses")
                        .HasForeignKey("UserPromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Definition");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("PromptSpark.ServiceDefinition.Database.GPTDefinition", b =>
                {
                    b.Navigation("GPTResponses");
                });

            modelBuilder.Entity("PromptSpark.ServiceDefinition.Database.GPTUserPrompt", b =>
                {
                    b.Navigation("GPTResponses");
                });
#pragma warning restore 612, 618
        }
    }
}
