// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PromptSpark.Domain.Data;

#nullable disable

namespace PromptSpark.Migrations.HazletonGPTDb
{
    [DbContext(typeof(GPTDbContext))]
    [Migration("20240416131932_AddPersonTraits")]
    partial class AddPersonTraits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("PromptSpark.ServiceDefinition.Database.GPTDefinition", b =>
                {
                    b.Property<int>("DefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageType")
                        .HasColumnType("TEXT");

                    b.Property<string>("model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<string>("temperature")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("DefinitionId");

                    b.ToTable("Definitions");
                });

            modelBuilder.Entity("PromptSpark.ServiceDefinition.Database.GPTUserPrompt", b =>
                {
                    b.Property<int>("ServiceDefintionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestPrompt")
                        .HasColumnType("TEXT");

                    b.HasKey("ServiceDefintionId");

                    b.HasIndex("TestPrompt")
                        .IsUnique();

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("PromptSpark.ServiceDefinition.Database.GPTDefinitionResponse", b =>
                {
                    b.Property<int>("ServiceDefintionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserPromptId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemResponse")
                        .HasColumnType("TEXT");

                    b.HasKey("ServiceDefintionId");

                    b.HasIndex("DefinitionId");

                    b.HasIndex("UserPromptId");

                    b.ToTable("DefinitionResponses");
                });

            modelBuilder.Entity("PromptSpark.ServiceDefinition.Database.PersonaTrait", b =>
                {
                    b.Property<int>("TraitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GPTDefinitionDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trait")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("TraitId");

                    b.HasIndex("GPTDefinitionDefinitionId");

                    b.ToTable("PersonaTraits");
                });

            modelBuilder.Entity("PromptSpark.ServiceDefinition.Database.GPTDefinitionResponse", b =>
                {
                    b.HasOne("PromptSpark.ServiceDefinition.Database.GPTDefinition", "Definition")
                        .WithMany("GPTResponses")
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PromptSpark.ServiceDefinition.Database.GPTUserPrompt", "Response")
                        .WithMany("GPTResponses")
                        .HasForeignKey("UserPromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Definition");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("PromptSpark.ServiceDefinition.Database.PersonaTrait", b =>
                {
                    b.HasOne("PromptSpark.ServiceDefinition.Database.GPTDefinition", null)
                        .WithMany("PersonaTraits")
                        .HasForeignKey("GPTDefinitionDefinitionId");
                });

            modelBuilder.Entity("PromptSpark.ServiceDefinition.Database.GPTDefinition", b =>
                {
                    b.Navigation("GPTResponses");

                    b.Navigation("PersonaTraits");
                });

            modelBuilder.Entity("PromptSpark.ServiceDefinition.Database.GPTUserPrompt", b =>
                {
                    b.Navigation("GPTResponses");
                });
#pragma warning restore 612, 618
        }
    }
}
