namespace PromptSpark.Areas.OpenAI.Models.OpenAI;

public class Choice
{
    /// <summary>
    /// The index position of this choice if multiple completions were requested.
    /// </summary>
    public int Index { get; set; }
    /// <summary>
    /// The text of the chat completion generated by the model.
    /// </summary>
    public Message Message { get; set; }
    public dynamic Logprobs { get; set; }
    public string FinishReason { get; set; }
    /// <summary>
    /// Additional properties associated with the completion, such as log probabilities, if requested.
    /// </summary>
    public Dictionary<string, object> AdditionalProperties { get; set; }
}
