global using ControlSpark.Domain.Entities;
global using ControlSpark.Domain.Models;
global using ControlSpark.Domain.ViewModels;
global using System;
global using System.Collections.Generic;
global using System.ComponentModel;
global using System.ComponentModel.DataAnnotations;
global using System.Globalization;
global using System.Text.Json.Serialization;
