global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.RazorPages;
global using Microsoft.AspNetCore.WebUtilities;
global using System.Text;
global using WebSpark.UserIdentity.Data;
global using Microsoft.EntityFrameworkCore;
global using WebSpark.Portal.Utilities;
