@WebSpark.Portal_HostAddress = https://localhost:55863

@id=string
POST {{WebSpark.Portal_HostAddress}}/{area:exists}/jshowadmin/deleteconfirmed/{{id}}

###

@location="Dallas"
GET {{WebSpark.Portal_HostAddress}}/api/AsyncSpark/openweatherapi/weather?location=Dallas

###
